"""
ToolRecall CLI — toolrecall status, stats, invalidate, index.

Nutzung:
    toolrecall status          # Cache-Status anzeigen
    toolrecall stats           # Detaillierte Statistiken
    toolrecall invalidate      # Cache leeren
    toolrecall index           # Wissensdatenbank indizieren
    toolrecall serve           # HTTP-Proxy starten (Fallback, empfohlen: nginx)
    toolrecall nginx           # Nginx-Config generieren/installieren
"""
import os, sys, json


def cmd_status():
    """Cache-Status anzeigen."""
    from toolrecall.cache import get_stats
    stats = get_stats()
    print("=" * 50)
    print("  ToolRecall Status")
    print("=" * 50)
    for k, v in stats.items():
        if isinstance(v, dict):
            print(f"  {k}: {v['hits']} hits, {v['misses']} misses, " +
                  f"hit_rate={v['hit_rate']}, tokens_saved={v['tokens_saved']:,}")
        else:
            print(f"  {k}: {v}")


def cmd_stats():
    """Detaillierte Statistiken als JSON."""
    from toolrecall.cache import get_stats
    print(json.dumps(get_stats(), indent=2))


def cmd_invalidate():
    """Cache leeren."""
    from toolrecall.cache import invalidate_all
    invalidate_all()
    print("ToolRecall cache cleared.")


def cmd_index():
    """Wissensdatenbank indizieren."""
    from toolrecall.docs import index_all, DB_PATH
    print("Indexing knowledge database...")
    total = index_all()
    print(f"Done. {total} pages indexed.")
    print(f"Database: {DB_PATH}")


def cmd_serve():
    """HTTP-Proxy starten (Fallback, empfohlen: nginx davor)."""
    from toolrecall.cache import cached_read, cached_skill, cached_terminal
    from toolrecall.docs import docs_search, docs_get_page
    from toolrecall.config import load_config
    import http.server
    import json

    cfg = load_config()
    port = cfg.proxy_port
    bind = cfg.proxy_bind

    class ToolRecallHandler(http.server.BaseHTTPRequestHandler):
        def do_GET(self):
            path = self.path.split("?")[0]
            q = {k: v for k, v in (p.split("=") for p in self.path.split("?")[1:] if "=" in p)}

            if path == "/cached_read":
                p = q.get("path", "")
                result = cached_read(p)
            elif path == "/cached_skill":
                s = q.get("name", "")
                result = cached_skill(s)
            elif path == "/cached_terminal":
                c = q.get("cmd", "")
                ttl = int(q.get("ttl", "0")) or None
                result = cached_terminal(c, ttl)
            elif path == "/docs_search":
                query = q.get("query", "")
                src = q.get("source", None)
                result = {"output": docs_search(query, src)}
            elif path == "/health":
                result = {"status": "ok", "version": "0.1.0"}
            else:
                result = {"error": f"Unknown endpoint: {path}"}

            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(json.dumps(result).encode())

        def log_message(self, fmt, *args):
            pass  # Leise

    server = http.server.HTTPServer((bind, port), ToolRecallHandler)
    print(f"ToolRecall HTTP proxy running on http://{bind}:{port}")
    print(f"Endpoints:")
    print(f"  GET /cached_read?path=/pfad/datei")
    print(f"  GET /cached_skill?name=skill-name")
    print(f"  GET /cached_terminal?cmd=git status")
    print(f"  GET /docs_search?query=suchbegriff")
    print(f"  GET /health")
    print()
    print("Recommended: put nginx in front for SSL + auth.")
    print("  toolrecall nginx  →  generates nginx config")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nShutting down.")


def cmd_nginx():
    """Nginx-Config generieren."""
    cfg_dir = os.path.expanduser("~/.toolrecall")
    os.makedirs(cfg_dir, exist_ok=True)
    out_path = os.path.join(cfg_dir, "nginx-toolrecall.conf")

    nginx_cfg = """# ToolRecall — Nginx Reverse Proxy Config
# Generated by `toolrecall nginx`
# Place in /etc/nginx/sites-available/toolrecall
# Then: ln -s /etc/nginx/sites-available/toolrecall /etc/nginx/sites-enabled/
# Then: nginx -t && systemctl reload nginx

server {
    listen 80;
    server_name localhost;

    # === WICHTIG: Nginx selbst cached NICHT ===
    # ToolRecall verwaltet seinen eigenen Cache (SQLite)
    # Nginx ist NUR SSL-Terminator + Router
    proxy_cache off;
    proxy_no_cache 1;
    proxy_cache_bypass 1;

    location /toolrecall/ {
        proxy_pass http://[IP_ADDRESS]:8511/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Timeouts (ToolRecall ist schnell, aber LLM kann langsam sein)
        proxy_connect_timeout 5s;
        proxy_read_timeout 30s;
        proxy_send_timeout 30s;
    }

    # Optional: Passwort-Schutz
    # location /toolrecall/ {
    #     auth_basic "ToolRecall";
    #     auth_basic_user_file /etc/nginx/.htpasswd_toolrecall;
    #     proxy_pass http://[IP_ADDRESS]:8511/;
    # }
}

# SSL-Version (empfohlen)
# server {
#     listen 443 ssl;
#     server_name toolrecall.dev;
#
#     ssl_certificate /etc/letsencrypt/live/toolrecall.dev/fullchain.pem;
#     ssl_certificate_key /etc/letsencrypt/live/toolrecall.dev/privkey.pem;
#
#     location /toolrecall/ {
#         proxy_pass http://[IP_ADDRESS]:8511/;
#     }
# }
"""
    with open(out_path, "w") as f:
        f.write(nginx_cfg)
    print(f"Nginx config written to: {out_path}")
    print()
    print("To install:")
    print(f"  sudo cp {out_path} /etc/nginx/sites-available/toolrecall")
    print("  sudo ln -s /etc/nginx/sites-available/toolrecall /etc/nginx/sites-enabled/")
    print("  sudo nginx -t && sudo systemctl reload nginx")
    print()
    print("To add password protection:")
    print("  sudo apt install apache2-utils")
    print("  sudo htpasswd -c /etc/nginx/.htpasswd_toolrecall yourpassword")
    print("  # Then uncomment the auth_basic lines in the config above")


def main():
    if len(sys.argv) < 2:
        print("Usage: toolrecall <command>")
        print()
        print("Commands:")
        print("  status       Cache status and stats")
        print("  stats        Detailed stats (JSON)")
        print("  invalidate   Clear all caches")
        print("  index        Build/update knowledge database")
        print("  serve        Start HTTP proxy (fallback, nginx recommended)")
        print("  nginx        Generate nginx config")
        return

    cmd = sys.argv[1]
    commands = {
        "status": cmd_status,
        "stats": cmd_stats,
        "invalidate": cmd_invalidate,
        "index": cmd_index,
        "serve": cmd_serve,
        "nginx": cmd_nginx,
    }

    if cmd in commands:
        commands[cmd]()
    else:
        print(f"Unknown command: {cmd}")
        print("Available: status, stats, invalidate, index, serve, nginx")