"""ToolRecall CLI -- toolrecall status, stats, invalidate, index, serve, nginx.

Usage:
    toolrecall status          # Show cache status
    toolrecall stats           # Detailed statistics
    toolrecall invalidate      # Clear cache
    toolrecall index           # Index knowledge base
    toolrecall serve           # Start HTTP proxy (fallback, nginx recommended)
    toolrecall nginx           # Generate nginx config
"""
import os, sys, json
def cmd_status():
    """Show cache status."""
    from toolrecall.cache import get_stats
    stats = get_stats()
    print("=" * 50)
    print("  ToolRecall Status")
    print("=" * 50)
    for k, v in stats.items():
        if isinstance(v, dict):
            print(f"  {k}: {v['hits']} hits, {v['misses']} misses, " +
                  f"hit_rate={v['hit_rate']}, tokens_saved={v['tokens_saved']:,}")
        else:
            print(f"  {k}: {v}")


def cmd_stats():
    """Detailed statistics as JSON."""
    from toolrecall.cache import get_stats
    print(json.dumps(get_stats(), indent=2))


def cmd_invalidate():
    """Clear cache."""
    from toolrecall.cache import invalidate_all
    invalidate_all()
    print("ToolRecall cache cleared.")


def cmd_index():
    """Index knowledge base."""
    from toolrecall.docs import index_all, DB_PATH
    print("Indexing knowledge database...")
    total = index_all()
    print(f"Done. {total} pages indexed.")
    print(f"Database: {DB_PATH}")


def cmd_serve():
    """Start HTTP proxy (delegates to toolrecall.proxy)."""
    from toolrecall.proxy import run_server
    from toolrecall.config import load_config

    cfg = load_config()
    run_server(bind=cfg.proxy_bind, port=cfg.proxy_port)


def cmd_mcp():
    """Start ToolRecall MCP server (exposes cache/search as MCP tools)."""
    from toolrecall.mcp_server import main as mcp_main
    mcp_main()


def cmd_nginx():
    """Generate nginx config."""
    cfg_dir = os.path.expanduser("~/.toolrecall")
    os.makedirs(cfg_dir, exist_ok=True)
    out_path = os.path.join(cfg_dir, "nginx-toolrecall.conf")

    nginx_cfg = """# ToolRecall — Nginx Reverse Proxy Config
# Generated by `toolrecall nginx`
# Place in /etc/nginx/sites-available/toolrecall
# Then: ln -s /etc/nginx/sites-available/toolrecall /etc/nginx/sites-enabled/
# Then: nginx -t && systemctl reload nginx

server {
    listen 80;
    server_name localhost;

    # === IMPORTANT: Nginx itself does NOT cache ===
    # ToolRecall manages its own cache (SQLite)
    # Nginx is ONLY SSL terminator + router
    proxy_cache off;
    proxy_no_cache 1;
    proxy_cache_bypass 1;

    location /toolrecall/ {
        proxy_pass http://127.0.0.1:8567/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Timeouts (ToolRecall is fast, but LLM can be slow)
        proxy_connect_timeout 5s;
        proxy_read_timeout 30s;
        proxy_send_timeout 30s;
    }

    # Optional: Password protection
    # location /toolrecall/ {
    #     auth_basic "ToolRecall";
    #     auth_basic_user_file /etc/nginx/.htpasswd_toolrecall;
    #     proxy_pass http://[IP_ADDRESS]:8567/;
    # }
}

# SSL Version (recommended)
# server {
#     listen 443 ssl;
#     server_name toolrecall.dev;
#
#     ssl_certificate /etc/letsencrypt/live/toolrecall.dev/fullchain.pem;
#     ssl_certificate_key /etc/letsencrypt/live/toolrecall.dev/privkey.pem;
#
#     location /toolrecall/ {
#         proxy_pass http://[IP_ADDRESS]:8567/;
#     }
# }
"""
    with open(out_path, "w") as f:
        f.write(nginx_cfg)
    print(f"Nginx config written to: {out_path}")
    print()
    print("To install:")
    print(f"  sudo cp {out_path} /etc/nginx/sites-available/toolrecall")
    print("  sudo ln -s /etc/nginx/sites-available/toolrecall /etc/nginx/sites-enabled/")
    print("  sudo nginx -t && sudo systemctl reload nginx")
    print()
    print("To add password protection:")
    print("  sudo apt install apache2-utils")
    print("  sudo htpasswd -c /etc/nginx/.htpasswd_toolrecall yourpassword")
    print("  # Then uncomment the auth_basic lines in the config above")


def main():
    if len(sys.argv) < 2:
        print("Usage: toolrecall <command>")
        print()
        print("Commands:")
        print("  status       Cache status and stats")
        print("  stats        Detailed stats (JSON)")
        print("  invalidate   Clear all caches")
        print("  index        Build/update knowledge database")
        print("  serve        Start HTTP proxy (fallback, nginx recommended)")
        print("  nginx        Generate nginx config")
        return

    cmd = sys.argv[1]
    commands = {
        "status": cmd_status,
        "stats": cmd_stats,
        "invalidate": cmd_invalidate,
        "index": cmd_index,
        "serve": cmd_serve,
        "nginx": cmd_nginx,
        "mcp": cmd_mcp,
    }

    if cmd in commands:
        commands[cmd]()
    else:
        print(f"Unknown command: {cmd}")
        print("Available: status, stats, invalidate, index, serve, nginx, mcp")